[build]
  command = "npm run build"
  publish = "build"
  environment = { NODE_ENV = "https://backtest-production-7f88.up.railway.app" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
