[build]
  command = "yarn build"  # Cambia a "npm run build" si usas npm
  publish = "build"       # Carpeta donde están los archivos listos para despliegue
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
